import { Header,Hero } from "../components"

export default function Home() {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0">
      <div>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </div>
      <Header/>
      <section id="hero" className="snap-center"> 
        <Hero/>
      </section>
      {/* {About} */}
      {/* {Experience} */}
      {/* {Skills} */}
      {/* {Projects} */}
      {/* {Contact Me} */}
    </div>
  )
}
